name: Linux Ubuntu

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        install: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y libopenmpi-dev libomp5 libomp-dev libnuma-dev freeglut3-dev \
          libreadline-dev libsqlite3-dev tk-dev python-openssl ninja-build
        curl -L -O https://github.com/Kitware/CMake/releases/download/v3.16.4/cmake-3.16.4-Linux-x86_64.sh
        chmod +x cmake-3.16.4-Linux-x86_64.sh
        sudo ./cmake-3.16.4-Linux-x86_64.sh --skip-license --prefix=/usr/local
        curl https://pyenv.run | bash
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init -)"
        PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.6.9
        pyenv shell 3.6.9

    - name: Checkout BioDynaMo
      uses: actions/checkout@v2

    - name: Get BioDynaMo git version history
      shell: bash
      run: |
        git fetch --unshallow
        git fetch --tags origin
        git remote set-branches --add origin master

    - name: Build BioDynaMo
      shell: bash
      run: |
        cmake -G Ninja -Dopencl=OFF -Dparaview=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -B build
        cmake --build build --parallel --config Release

    - name: Unit tests BioDynaMo
      shell: bash
      if: matrix.install == 'false'
      working-directory: build
      run: |
        . bin/thisbdm.sh
        bin/biodynamo-unit-tests

    - name: Installation tests BioDynaMo
      shell: bash
      if: matrix.install == 'true'
      run: |
        export DISPLAY=:99.0
        util/xvfb-initd.sh start
        test/installation-test.sh
        util/xvfb-initd.sh stop

    - name: Create BioDynaMo archive
      if: github.event.action == 'published'
      shell: bash
      run: |
        mkdir artifact
        7z a artifact/biodynamo-mac.zip ./build

    - name: Upload BioDynaMo archive
      if: github.event.action == 'published'
      uses: actions/upload-artifact@v1
      with:
        name: biodynamo-binary-archives
        path: artifact

    - name: Upload release asset
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./artifact/biodynamo-mac.zip
        asset_name: biodynamo-mac.zip
        asset_content_type: application/zip
